rvm:
  - 2.6.2
sudo: false
language: ruby
# before_install:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
services:
  - postgresql
addons:
  chrome: stable
before_script:
  - "bin/rake db:create db:migrate"
