version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:1
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: postgresql://postgres@db/illyan_development
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
